### ISSUE TITLE
Замечания по CMyString

### ISSUE THREAD

**Issue by alexey-malov** [matjukov-nikolaj/OOP#24]
- [ ] Бинарные операторы объявить вне класса, тогда за счёт конструктора с одим параметром можно будет выполнять сравнение std строк как слева, так и справа

**Comment by alexey-malov** [comment]
```c++
void CMyString::Clear()
{
	if (m_pChars)
	{
		m_pChars.reset();
	}
	m_length = 0;
}
```
- [ ] Проверка избыточна. reset безопасно вызывать при нулевом указателе

**Comment by alexey-malov** [comment]
```c++
CMyString::CMyString(const char* pString, size_t length)
{
	m_pChars = std::make_unique<char[]>(length + 1);
	memcpy(m_pChars.get(), pString, length + 1); // <-----------
	m_length = length;
	m_pChars[length] = '\0';
}
```
- [ ] Нельзя обращаться к элементу за пределами 0..length-1

**Comment by alexey-malov** [comment]
```c++
const char* CMyString::GetStringData() const
{
	const char zeroLengthString[] = "";
	return m_pChars ? m_pChars.get() : zeroLengthString;
}
```

- [ ] При пустом m_pChars вернётся указатель на первый элемент удалённого временного массива. Добавить проверку в тесты

**Comment by alexey-malov** [comment]
```c++
CMyString const CMyString::operator+(const CMyString& string) const
{
	auto tmp = std::make_unique<char[]>(m_length + string.m_length + 1);
	memcpy(tmp.get(), m_pChars.get(), m_length);
	memcpy(tmp.get() + m_length, string.m_pChars.get(), string.m_length + 1);
	tmp[m_length + string.m_length] = '\0';

	return CMyString(tmp.get(), m_length + string.m_length);
}
```
- [ ] Сперва создаётся временный массив, куда копируются символы строк, а затем создаётся новая строка, которая копирует содержимого временного массива, после чего временный массив удаляется. Избежать копирования. Например, за счёт приватного конструктора, принимающего unique_ptr

**Comment by alexey-malov** [comment]
- [ ] Лучше везде возвращать CMyString, а не const CMyString, чтобы можно было перемещать содержимое.

**Comment by alexey-malov** [comment]
```c++
CMyString const CMyString::operator+=(const CMyString& string)
{
	return *this = *this + string;
}
```

- [ ] Оператор += будет неправильно работать в такой ситуации:
```c++
(x += y) += z;
```
Исправить, проверить в тестах

**Comment by alexey-malov** [comment]
```c++
char const& CMyString::operator[](size_t index) const
{
	if ((index >= m_length) || (index < 0))
	{
		throw std::out_of_range("Index is out of range");
	}

	return m_pChars[index];
}

char& CMyString::operator[](size_t index)
{
	if ((index >= m_length) || (index < 0))
	{
		throw std::out_of_range("Index is out of range");
	}

	return m_pChars[index];
}
```

- [ ] Беззнаковый тип не может принимать значения < 0

**Comment by alexey-malov** [comment]
```c++
bool CMyString::operator<(const CMyString& string) const
{
	if (m_length == string.m_length)
	{
		return (memcmp(m_pChars.get(), string.m_pChars.get(), m_length) < 0);
	}
	return (m_length < string.m_length);
}
```

- [ ] Неправильно будет работать в ситуации: "alligator" < "zebra". Ожидается результат будет true, у вас же возвращается false. С остальными операторами то же самое.

**Comment by alexey-malov** [comment]
```c++
std::ostream& operator<<(std::ostream& strm, const CMyString& string)
{
	strm << string.GetStringData();

	return strm;
}
```

- [ ] Не будут выведены символы, следующие за \0 в середине строки. Исправить, проверить в тестах

**Comment by AniSkyWorker** [comment]
- [ ] бинарные операторы можно вынести из класса, для того, чтобы не объявлять их как friend

**Comment by AniSkyWorker** [comment]
- [ ] в местах, где используются сишные `memcmp` и `memcpy` нужно добавить проверки на nullptr, если он будет передан в функции, возникнет неопределенное поведение

**Comment by AniSkyWorker** [comment]
- [ ] протестить работу класса со строкой в середине которой символ \0(конструктор, получение длинны, сравнение)
