### ISSUE TITLE
Замечания по ReplaceInString

### ISSUE THREAD

**Issue by alexey-malov** [matjukov-nikolaj/OOP#7]
https://github.com/matjukov-nikolaj/OOP/blob/1a4a5cf7803532b5c70c53da3f19076ade53530c/lw01/replace/replace/replace.cpp#L7-L39

- [x] Вместо посимвольного копирования лучше использовать append. Будет быстрее работать

**Comment by oMystique** [comment]
- [ ] Можно обойтись без явного сравнения размера строки с 0. У std::string есть метод `.empty()`
```c++
	if ((searchStr.size() == 0) || (str.size() == 0))
	{
		return str;
	}
```

- [ ] Странное имя для объекта типа std::string. "Заменить строку"?
```c++
const string &replaceStr
```

**Comment by oMystique** [comment]
- [ ] Лучше разделять фрагменты кода переносами строк на логические блоки - это улучшает восприятие написанного
```c++
int main(int argc, char* argv[])
{
	if (argc != 5)
	{
		cout << "Incorrect number of parameters." << endl;
		cout << "Write so: replace.exe <input file> <output file> <search string> <replace string>" << endl;
		return 1;
	}
	ifstream fileIn(argv[1]);
	if (!fileIn.is_open())
	{
		cout << "File " << argv[1] << " has not opened for reading.";
		return 1;
	}
	ofstream fileOut(argv[2]);
	if (!fileOut.is_open())
	{
		cout << "File " << argv[2] << " has not opened for writing.";
		return 1;
	}
	const string searchString = argv[3];
	const string replaceString = argv[4];
	if (!ReplaceInFile(fileIn, fileOut, searchString, replaceString))
	{
		cout << "Failed to write data on disk." << endl;
		return 1;
	}
	return 0;
}
```

к примеру,

```c++
	ofstream fileOut(argv[2]);

	if (!fileOut.is_open())
	{
		cout << "File " << argv[2] << " has not opened for writing.";
		return 1;
	}

	const string searchString = argv[3];
	const string replaceString = argv[4];

	if (!ReplaceInFile(fileIn, fileOut, searchString, replaceString))
	{
		cout << "Failed to write data on disk." << endl;
		return 1;
	}

	return 0;
```

**Comment by oMystique** [comment]
- [x] При прогоне программы в выходном файле появляется лишний перенос строки. Параметры `input.txt output.txt 123 123`
![default](https://user-images.githubusercontent.com/14878773/36759877-e2caf974-1c29-11e8-8035-36c3a47786f9.png)

**Comment by alexey-malov** [comment]
@oMystique, добавление символа перевода строки в самом конце вполне допустим
